project:
  type: website
  output-dir: "../docs"

website:
  title: "Minnesota Animal Movement Archive"
  favicon: "figures/favicon_new.png"
  navbar:
    title: false
    logo: "figures/navbar_logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      - text: Participate
        menu: 
          - text: Submission Guide
            href: submission_guide.qmd
          - text: Participation Agreement
            href: participation_agreement.qmd
      - href: about.qmd
        text: About Us

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true