---
title: "Participating Studies"
execute:
  echo: false
format: 
  html:
    page-layout: full
    toc: false
    code-fold: false
---


```{r setup, include=FALSE}
library(DT)
library(move2)
library(dplyr)
library(stringr)

username <- Sys.getenv("MOVEBANK_USERNAME")
password <- Sys.getenv("MOVEBANK_PASSWORD")

# Set up Movebank credentials and get data
move2::movebank_store_credentials(
  username = username,
  password = password
)

# Download study details
studies <- move2::movebank_download_study_info(i_am_collaborator=TRUE)
```

This initiative began summer of 2025 and the archive is actively growing. If you'd like your study to be included in the archive, checkout our [Submission Guide](submission_guide.qmd).
<br>
<br>

```{r display-table, output=TRUE, warning=FALSE}
# Display the interactive table

table_data <- studies |>
  dplyr::mutate(
    linked_name = paste0(
      '<a href="https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study',
      id,
      '" target="_blank">',
      name,
      "</a>"
    ),
    formatted_pi = case_when(
      str_detect(principal_investigator_name, "\\(.*\\)") ~
        str_extract(principal_investigator_name, "(?<=\\()[^)]+(?=\\))"),
      TRUE ~ principal_investigator_name
    ),
    formatted_taxon_ids = case_when(
      is.na(taxon_ids) | taxon_ids == "" ~ "",
      TRUE ~ str_replace_all(taxon_ids, "([^,]+)", "<em>\\1</em>") |>
        str_replace_all(",", ", ")
    ),
    formatted_sensor_type_ids = gsub(",", ", ", sensor_type_ids),
    formatted_start_time = format(timestamp_first_deployed_location, "%m/%d/%Y"),
    formatted_latest_time = format(timestamp_last_deployed_location, "%m/%d/%Y")
  ) |>
  dplyr::select(
    linked_name,
    formatted_pi,
    formatted_taxon_ids,
    number_of_individuals,
    formatted_start_time,
    formatted_latest_time,
    formatted_sensor_type_ids
  )


DT::datatable(
  table_data,
  options = list(
    pageLength = 10,
    scrollX = TRUE
  ),
  colnames = c(
    "Study Name",
    "Principal Investigator",
    "Animal Taxon",
    "No. of Animals",
    "First Deployment",
    "Latest Deployment",
    "Sensor Type"
  ),
  escape = FALSE
)
```
